# Utiliser une version plus récente et supportée d'Ubuntu
FROM ubuntu:20.04

# Mettre à jour le mainteneur (utiliser LABEL est la pratique recommandée maintenant)
LABEL maintainer="Sreekanth G S <mail@sreekanth.in>"

# Définir le frontend non interactif pour Docker build
ENV DEBIAN_FRONTEND=noninteractive

# Mise à jour du système et installation des pré-requis
RUN apt-get update && \
    apt-get install -y software-properties-common locales && \
    locale-gen en_US.UTF-8

# Configuration des variables d'environnement pour la localisation
ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US:en \
    LC_ALL=en_US.UTF-8

# Ajout du PPA pour PHP depuis Ondrej
RUN add-apt-repository ppa:ondrej/php && \
    apt-get update

# Installation des paquets nécessaires
RUN apt-get install -y apache2-bin libapache2-mod-php php-curl php-ldap php-mysql php-mcrypt \
    php-gd php-xml patch curl vim git mysql-client wget unzip

# Activation des modules PHP et Apache nécessaires
RUN phpenmod mcrypt gd && \
    a2enmod xml2enc rewrite

# Confirmer que les fichiers php.ini existent et modifier la configuration de PHP
RUN find /etc/php/ -name php.ini -exec echo Found ini file at: {} \; && \
    find /etc/php/ -name php.ini -exec sed -i 's/variables_order = .*/variables_order = "EGPCS"/' {} \;

# Créer le groupe sentrifugo et ajouter l'utilisateur pour Apache
RUN groupadd sentrifugo && \
    useradd --uid 1000 --gid sentrifugo --create-home --shell /bin/bash docker && \
    echo "export APACHE_RUN_USER=docker" >> /etc/apache2/envvars && \
    echo "export APACHE_RUN_GROUP=sentrifugo" >> /etc/apache2/envvars

# Configuration des sites par défaut d'Apache
COPY 000-default.conf /etc/apache2/sites-enabled/000-default.conf

# Assurez-vous que le répertoire /var/www/html existe
RUN mkdir -p /var/www/html

# Télécharger et préparer Sentrifugo
RUN wget -q "http://www.sentrifugo.com/home/downloadfile?file_name=Sentrifugo.zip" -O Sentrifugo.zip && \
    unzip Sentrifugo.zip && \
    mv Sentrifugo_3.2 /var/www/html/sentrifugo && \
    chown -R docker:sentrifugo /var/www/html/sentrifugo

WORKDIR /var/www/html/sentrifugo

# Copier le script entrypoint
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Attribuer les permissions nécessaires pour Sentrifugo
RUN chmod 777 -R public/downloads public/uploads public/email_constants.php \
    public/emptabconfigure.php \
    public/site_constants.php \
    public/db_constants.php \
    public/application_constants.php \
    public/mail_settings_constants.php \
    logs/application.log \
    application/modules/default/plugins/AccessControl.php \
    install

# Définir les volumes pour les téléchargements et les téléversements
VOLUME ["/var/www/html/sentrifugo/public/uploads", "/var/www/html/sentrifugo/public/downloads"]

# Point d'entrée
ENTRYPOINT ["/entrypoint.sh"]

# Exposer le port 80
EXPOSE 80
# Configure Apache and restart
RUN a2ensite sentrifugo && \
    a2enmod rewrite && \
    service apache2 restart && \
    rm /var/www/html/index.html

# Start Apache
CMD ["apache2ctl", "-D", "FOREGROUND"]
