version: '3.9'  # Use a recent version

services:
  sentrifugo:
    build:
      context: .  # Ensure Dockerfile is in the same directory or specify the path
      dockerfile: Dockerfile-sentrifugo
    container_name: sentrifugo
    ports:
      - "8080:80"  # HTTP
      - "8443:443" # HTTPS, ensure SSL is configured if using this in production
    depends_on:
      - mariadb
    restart: always

  mariadb:
    build:
      context: .  
      dockerfile: Dockerfile-mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sentrifugo_db
      MYSQL_USER: sentrifugo_user
      MYSQL_PASSWORD: sentrifugo_pass
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always

volumes:
  mariadb_data:
