version: '3.9'  # Mise à jour vers une sous-version plus récente qui supporte de nouvelles fonctionnalités

services:
  sentrifugo:
    build: ./Dockerfile-sentrifugo
    container_name: sentrifugo
    ports:
      - "8080:80"  # Exposition du port 80 sur le port 8080 de l'hôte
      - "8443:443" # Exposition du port 443 sur le port 8443 de l'hôte
    depends_on:
      - mariadb  # Utilisation de 'depends_on' au lieu de 'links'
    restart: always

  mariadb:
    build: ./Dockerfile-mariadb
    container_name: mariadb
    # Si le port MariaDB doit être accessible depuis l'hôte, décommentez la ligne suivante :
    # ports:
    #   - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword  # Définir un mot de passe root (changez 'rootpassword' pour votre mot de passe)
      - MYSQL_DATABASE=sentrifugo_db      # Nom de la base de données à créer
      - MYSQL_USER=sentrifugo_user        # Nom de l'utilisateur de la base de données
      - MYSQL_PASSWORD=sentrifugo_pass    # Mot de passe pour l'utilisateur de la base de données
    volumes:
      - mariadb_data:/var/lib/mysql  # Persistance des données MariaDB
 restart: always
# Réseaux pour la communication entre conteneurs
networks:
  default:
    driver: bridge
