# Use a more recent and supported version of Ubuntu
FROM ubuntu:20.04

# Update maintainer information
LABEL maintainer="Sreekanth G S <mail@sreekanth.in>"

# Set non-interactive frontend (prevents some prompts)
ENV DEBIAN_FRONTEND=noninteractive

# Install prerequisites, update system and install packages
RUN apt-get update && \
    apt-get install -y software-properties-common locales && \
    locale-gen en_US.UTF-8 && \
    add-apt-repository ppa:ondrej/php && \
    apt-get update && \
    apt-get install -y apache2 libapache2-mod-php php-curl php-ldap php-mysql php-mcrypt \
    php-gd php-xml patch curl vim git mysql-client wget unzip && \
    # Clean up to reduce layer size
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set environment variables for localization
ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US:en \
    LC_ALL=en_US.UTF-8

# Enable PHP and Apache modules
RUN phpenmod mcrypt gd && \
    a2enmod xml2enc rewrite

# Configure php.ini files
RUN find /etc/php/ -name php.ini -exec sed -i 's/variables_order = .*/variables_order = "EGPCS"/' {} \;

# Create a group and user for Apache
RUN groupadd sentrifugo && \
    useradd --uid 1000 --gid sentrifugo --create-home --shell /bin/bash docker && \
    echo "export APACHE_RUN_USER=docker" >> /etc/apache2/envvars && \
    echo "export APACHE_RUN_GROUP=sentrifugo" >> /etc/apache2/envvars

# Set the ServerName globally to suppress a message
RUN echo 'ServerName localhost' >> /etc/apache2/apache2.conf

# Configure the default Apache site
COPY 000-default.conf /etc/apache2/sites-available/
RUN a2ensite 000-default.conf

# Ensure the HTML directory exists
RUN mkdir -p /var/www/html

# Download and prepare Sentrifugo
RUN wget -q "http://www.sentrifugo.com/home/downloadfile?file_name=Sentrifugo.zip" -O Sentrifugo.zip && \
    unzip Sentrifugo.zip && \
    mv Sentrifugo_3.2 /var/www/html/sentrifugo && \
    chown -R docker:sentrifugo /var/www/html/sentrifugo && \
    # Set secure file permissions
    find /var/www/html/sentrifugo -type d -exec chmod 750 {} \; && \
    find /var/www/html/sentrifugo -type f -exec chmod 640 {} \;

# Set the working directory
WORKDIR /var/www/html/sentrifugo

# Declare volumes for uploads and downloads
VOLUME ["/var/www/html/sentrifugo/public/uploads", "/var/www/html/sentrifugo/public/downloads"]

# Expose port 80 for HTTP traffic
EXPOSE 80

# Start Apache in the foreground
CMD ["apache2ctl", "-D", "FOREGROUND"]
